config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true

  has_attached_file :image, styles: { medium: "640x" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand"><%= link_to 'Picogram', root_path%></div>
        </div>

          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li><%= link_to 'Login', '#'%></li>
            <li><%= link_to 'New', new_post_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Picgram</h1>

<div class="posts-wrapper row">
  <% if !@posts.nil? %>
    <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name"><%= 'Isaac Tullis' %></div>
      </div>
      <div class="image"><%= image_tag post.image(:medium) %></div>
      <div class='caption'><%= post.caption %></div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%= simple_form_for @post do |form| %>
  <%= form.input :image, as: :file %>
  <%= form.input :caption %>
  <%= form.button :submit %>
<% end %>